### ISSUE TITLE
project peer review

### ISSUE THREAD

**Issue by emilynsmith2** [agonzalezrubiosaab1/project#3]
Hello! I love the recipes on your website! Also I like your feedback form where you ask about the favorite cuisine! For the content, I think it would be cool to have your review on the recipes, and also maybe add a feature where you rate each recipe in terms of skill level. For technical issues maybe add a title to the image on the homepage, and  also on the homepage make the first blurb of text in a paragraph rather than h3

**Comment by agonzalezrubiosaab1** [comment]
thank you for the feedback
