### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ylevy1** [agonzalezrubiosaab1/project#4]
https://github.com/agonzalezrubiosaab1/project/blob/4e488a7f0a3a728bc2590fae24c913242f0792a1/index.html#L20
I really like your website because it is very informative and is well structured. The home page gives a quick summary of what we can expect throughout the pages which is helpful. I thought the "lets have some fun in the kitchen button was a good way to get people excited for the content on your other pages. I noticed there is a bug in line 20 where the image for the menu is not showing up on the website. Also, when you add style to the menu, you can consider adding it to an external style sheet since it will be the same on every page! Nice job overall!

**Comment by agonzalezrubiosaab1** [comment]
thank you yael I will check line 20
