### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by mosinowo1** [agonzalezrubiosaab1/project#5]
-  technical issues/bugs/suggestions:
1. Image is not showing up on index page; perhaps the image was not pushed to Github, or there is error in <img> tag in code
2. use text-align with <th>Latin Cuisine</th> and  <th>Dessert</th> so that is inline with the recipes under each category

- two suggestions on content
1. add an "about me" section so its more personable
2. add a section for social media handles ( instagram, twitter, etc.) that can pair nicely with your "email me" link

**Comment by agonzalezrubiosaab1** [comment]
thank you, will do
