### ISSUE TITLE
Peer Review - Noah Brown

### ISSUE THREAD

**Issue by noahbrown29** [agonzalezrubiosaab1/project#6]
Hi Ale,
Congratulations, you built a really pretty and useful website. I have a few issues that I wanted to bring to your attention. Firstly, I believe you meant to put an image at the top left of your homepage, but it will not load on my computer. This can be a tagging issue, maybe you used the wrong slash, or maybe you linked it to the wrong folder. Another thing I noticed is that you are using a table for your recipes. I think that this is a very good idea to keep things organized. One thing I would change would be to add a border to your table to make it more clear that there is separation. To do this, add "border" to your css and add a solid border color of probably around 1px. Additionally, for the recipe pages, I would put each step into a different "p" in order for your audience to be able to follow more easily. Other than that, I think your website is really great and will teach me a bunch of cool recipes that I will try in my suite with my friends. All of the recipes sound delicious and your website looks really well done. The contact form on your page also looks great but you have two comment boxes, one is probably enough :)

**Comment by agonzalezrubiosaab1** [comment]
thank you noah, I just fixed the image issue.
