### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ajosephs1** [agonzalezrubiosaab1/project#7]
Hi Alejandra,
I really like you're idea for you're website its very simple and very useful already because the content is easy to read and structured well. I spend a lot of time on websites like these and I'd say the most easy ones to follow have the preparation guide in and ordered list `ol` as opposed to an `ul` or in a paragraph block. I'm also not sure if there's supposed to be a logo or image at the top left of the screen beside "homepage" but it didn't load on my website. This could possibly be a sourcing problem, i.e. the folders aren't sequentially ordered or included or a tag problem. Also a major problem I wanted to add feedback on what my favourite cuisine was and  "Jamaican" wasn't an option so that may have been a mistake 😎. Other than that I'm sure with some style the website will look great and I'm looking forward to seeing future versions and possibly using it.

**Comment by agonzalezrubiosaab1** [comment]
thank you joseph
